version: '3.8'

networks:
  default:                                                                                                                                        
    name: test_project                                                                                                                                   
    driver: bridge

volumes:
  postgres_data: {}
  prometheus_data: {}
  grafana_data: {}

services:

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: on-failure
    tty: true
    ports:
    - "80:80"
    volumes:
    - ./data/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - jbpm
      - grafana
  postgres:
    image: postgres:9.6
    container_name: postgres_jbpm
    volumes:
    - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: jbpm
      POSTGRES_USER: jbpm
      POSTGRES_PASSWORD: jbpm
  jbpm:
    image: jboss/jbpm-server-full
    container_name: jbpm
    environment:
      JBPM_DB_DRIVER: postgres
      JBPM_DB_HOST: postgres
    depends_on:
    - postgres
  prometheus:                                                                                                                                    
    image: prom/prometheus:latest                                                                                                                
    container_name: prometheus                                                                                                                   
    volumes:                                                                                                                                     
      - ./data/prometheus/:/etc/prometheus/                                                                      
      - prometheus_data:/prometheus                                                                                          
    command:                                                                                                                                     
      - '--config.file=/etc/prometheus/prometheus.yml'                                                                                           
  node-exporter:                                                                                                                                 
    image: prom/node-exporter:latest                                                                                                             
    container_name: node-exporter-local                                                                                                                
    volumes:                                                                                                                                     
      - /proc:/host/proc:ro                                                                                                                      
      - /sys:/host/sys:ro                                                                                                                        
      - /:/rootfs:ro                                                                                                                             
    command:                                                                                                                                     
      - '--path.procfs=/host/proc'                                                                                                               
      - '--path.rootfs=/rootfs'                                                                                                                  
      - '--path.sysfs=/host/sys'                                                                                                                 
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
  grafana:                                                                                                                                       
    image: grafana/grafana:latest                                                                                                                
    container_name: grafana                                                                                                                      
    volumes:                                                                                                                                     
      - grafana_data:/var/lib/grafana
      - ./data/grafana/provisioning:/etc/grafana/provisioning                                                                                      
      - ./data/grafana/grafana_datasources:/etc/grafana/datasources                                                                       
      - ./data/grafana/grafana_dashboards:/etc/grafana/dashboards                                                                         
    environment:                                                                                                                                 
      - GF_SECURITY_ADMIN_USER=admin                                                                                                             
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
    - prometheus
    - node-exporter